### ISSUE TITLE
how to define some bitfiled like FieldOffset,but on bits?

### ISSUE THREAD

**Issue by sgf** [barncastle/BitsKit#2]
same bits but not same type map

like this:

public  struct RGB565
{
public byte R;
public  byte G;
public  byte B;
public  ushort RG;
public  ushort GB;
public  ushort RGB
}

in memory:
RGB=Union(RG,GB)=Union(R,G,B)

**Comment by barncastle** [comment]
Thanks for the question. This is a feature that is definitely lacking as there is currently no way to do integral type conversions.

At the moment the only way to do this is to use a memory backing type instead, i.e.:

```c#
[BitObject(BitOrder.LeastSignificant)]
public unsafe partial struct RGB565
{
    [BitField("R", 5, BitFieldType.Byte)]
    [BitField("G", 6, BitFieldType.Byte)]
    [BitField("B", 5, BitFieldType.Byte)]
    public fixed byte RGB[2];
}

// OR...

[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 2)]
[BitObject(BitsKit.BitOrder.LeastSignificant)]
public partial struct RGB565
{
    [BitField("R", 5, BitFieldType.Byte)]
    [BitField("G", 6, BitFieldType.Byte)]
    [BitField("B", 5, BitFieldType.Byte)]
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
    public byte[] RGB;
}
```  

I'm currently working on other things but will look into adding this. The `BitFieldAttribute` already supports a `BitFieldType` argument for memory types so will utilise that. This would then allow the following:

```c#
public partial struct RGB565
{
    [BitField("R", 5, BitFieldType.Byte)]
    [BitField("G", 6, BitFieldType.Byte)]
    [BitField("B", 5, BitFieldType.Byte)]
    public ushort RGB;
}
```

I'm also thinking of adding a new attribute for explicit casting. This would allow casting to types that implement an integral implicit/explicit operator.

**Comment by sgf** [comment]
In fact, I specifically defined RG GB, for example, I actually have some network packets.
Like this:

```C#
[BitObject(BitOrder.LeastSignificant)]
public partial struct VMsgHead
{
[EnumField("MsgType", 3, typeof(VMsgType))]
[EnumField("FrameType",2,FrameType)]
[EnumField("VideoCmd", 3, typeof(VideoCmd))]
[EnumField("AudioCmd", 3, typeof(AudioCmd))]
private byte _MsgCmd;

public uint Len;
}
```

I want VideoCmd and AudioCmd to be in the same memory. Read them differently by FrameType.

**Comment by barncastle** [comment]
That makes sense, I totally misunderstood the question! To achieve this you'd need to use an explicit struct combined with padding bits, i.e.,

```c#
[StructLayout(LayoutKind.Explicit, Pack = 1)]
[BitObject(BitOrder.LeastSignificant)]
partial struct VMsgHead
{
    [EnumField("MsgType", 3, typeof(VMsgType))]
    [EnumField("FrameType", 2, typeof(FrameType))]
    [EnumField("VideoCmd", 3, typeof(VideoCmd))]
    [FieldOffset(0)]
    private byte _MsgCmdA;

    [BitField(5)]               // padding bits
    [EnumField("AudioCmd", 3, typeof(AudioCmd))]
    [FieldOffset(0)]
    private byte _MsgCmdB;

    [FieldOffset(1)]
    public uint Len;
}
```

This creates two backing fields at the same memory address (`_MsgCmdA` & `_MsgCmdB`) and the unnamed `BitFieldAttribute`  aligns `AudioCmd` to the right bit offset.

This may not be the most elegant solution and might seem verbose, but it's a deliberate design choice. The aim was to keep the C# representation as close to C as possible, and this approximates a union (see below). This approach also eliminates the need for users to track bit offsets in regular use.

```c++
struct VMsgHead {
    union {
        struct {
            uint8_t MsgType : 3; 
            uint8_t FrameType : 2;  
            uint8_t VideoType : 3;  
        };
        struct {
            uint8_t : 5;            // padding bits
            uint8_t AudioType : 3; 
        };
    };
    
    unsigned int Len;
};
```

That being said, I'm open to adding a way to define the bit offset, like you do with the `FieldOffset` attribute, I'm just not sure how this would look.
